//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTTDN_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSKhoa
    {
        public int Id { get; set; }
        public int IdDTKhoa { get; set; }
        public System.DateTime ThoiGianKhoa { get; set; }
        public string LiDoKhoa { get; set; }
        public Nullable<int> SoNgayKhoa { get; set; }
        public bool DoiTuong { get; set; }
    }
}
