//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTTDN_Code
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLMaEntities : DbContext
    {
        public QLMaEntities()
            : base("name=QLMaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogDangNhap> LogDangNhaps { get; set; }
        public virtual DbSet<LogDangXuat> LogDangXuats { get; set; }
        public virtual DbSet<LSKhoa> LSKhoas { get; set; }
        public virtual DbSet<Ma> Mas { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
    }
}
